### ISSUE TITLE
RxJava 1.1.1 was released

### ISSUE THREAD

**Issue by vanniktech** [artem-zinnatullin/RxJavaProGuardRules#24]
I don't know whether or not any Proguard rules need to be modified or not.

**Comment by artem-zinnatullin** [comment]
Yup, I started reviewing changes between 1.1.0 and 1.1.1 yesterday, should
finish today and release new proguard rules.

On Mon, 15 Feb 2016, 04:37 Niklas Baudy notifications@github.com wrote:

> I don't know whether or not any Proguard rules need to be modified or not.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/artem-zinnatullin/RxJavaProGuardRules/issues/24.
> 
> ## 

@artem_zin

**Comment by artem-zinnatullin** [comment]
Closed by #25, should be available in 10-20 minutes.

**Comment by vanniktech** [comment]
:+1:
