### ISSUE TITLE
Can't be confirmed copyright owner of this project.

### ISSUE THREAD

**Issue by tumbling-dice** [artem-zinnatullin/RxJavaProGuardRules#35]
This library is claiming "Apache License, Version 2.0", but I couldn't find where copyright owner was written.

I'm using this library in my application. And I want to enumerate in my application all used library and its copyright owner.

I'm a little troubled.

Thanks.

**Comment by artem-zinnatullin** [comment]
ok, I see, made a PR for that #36

**Comment by artem-zinnatullin** [comment]
Closed by #36.
