### ISSUE TITLE
Rules for 1.1.9

### ISSUE THREAD

**Issue by Jawnnypoo** [artem-zinnatullin/RxJavaProGuardRules#37]
Just wanted to put this on your radar if you did not already know that 1.1.9 is out!

**Comment by artem-zinnatullin** [comment]
Hey hey, it's on my high priority list, I'm in Amsterdam at the moment,
will try do a release for 1.1.9 in couple days!

**Comment by Jawnnypoo** [comment]
Awesome! thanks for the great work!

**Comment by artem-zinnatullin** [comment]
@Jawnnypoo done! Should be available in 10-30 minutes

**Comment by Jawnnypoo** [comment]
Awesome! Appreciate it!
