### ISSUE TITLE
Remove last version int

### ISSUE THREAD

**Issue by danielgomezrico** [artem-zinnatullin/RxJavaProGuardRules#41]
The idea is to remove from version the `a.b.c.x` the `x`,

In my case I have an `ext` variable with `rxjava`version but to use it with this I need to add a `0` like:

```
rxProguard      : "com.artemzin.rxjava:proguard-rules:$ext.versions.rxJava.0@aar"
```

Or what's the idea of this number in the version?

**Comment by artem-zinnatullin** [comment]
Yo!

> Or what's the idea of this number in the version?

The idea is that if already released version of ProGuard rules has some problems, then we can do patch release without breaking versioning.

**Example:**

RxJava v1.2.0
Rules    v1.2.0

What if Rules v1.2.0 have problems? How can we update them and keep RxJava version consistent?

Well, only by adding "patch" version to Rules, i.e: Rules v1.2.0.0 so we could release v1.2.0.1 for RxJava v1.2.0!

Hope that answers the question!
