### ISSUE TITLE
Fix versioning to be more clear

### ISSUE THREAD

**Issue by jaredsburrows** [artem-zinnatullin/RxJavaProGuardRules#43]
Make this repo have the same version as `rxjava` to reuse the same variable.

See example `build.gradle`:

```
def rxJavaVersion = "1.2.1"

ext.deps = [
    rxJava                  : "io.reactivex:rxjava:$rxJavaVersion",
    rxJavaProguardRules     : "com.artemzin.rxjava:proguard-rules:${rxJavaVersion}.0"
]
```

I have to append a hardcoded ".0" at the end of the proguard rules dependency.

**Comment by JakeWharton** [comment]
What if multiple releases need to be made for a single RxJava version to
correct a rule?

**Comment by jaredsburrows** [comment]
If you release more `RxJava` versions, wouldn't you bump the current patch version (eg. `x.x.1`)? You would just mirror that number to this repo. So if RxJava becomes `1.2.2` then `1.2.3`. This repo would move to `1.2.2` then `1.2.3`.

**Comment by JakeWharton** [comment]
No, multiple releases of this project for a single release of RxJava.

**Comment by jaredsburrows** [comment]
Alright. I see what you are saying. That's a good idea. I'll go ahead and close.

**Comment by artem-zinnatullin** [comment]
@jaredsburrows this was also recently discussed (with example) in #41 if you're interested.

@JakeWharton thanks for help!
