### ISSUE TITLE
Check if ProGuard rules required for RxJava v2

### ISSUE THREAD

**Issue by artem-zinnatullin** [artem-zinnatullin/RxJavaProGuardRules#44]
RxJava v2 release is coming, this issue will collect info regarding ProGuard for RxJava v2.

// cc @vanniktech created this as continuation of our discussion.

**Comment by artem-zinnatullin** [comment]
Forgot to mention: if ProGuard rules won't be required for RxJava v2 — this project will be iceboxed since RxJava v2 has same requirements to runtime as RxJava v1 and is basically long-term replacement for v1.

If we'll see new releases of RxJava v1 after v2 release — I'll keep this project updated until I stop using v1 at work, then I'll switch to community (PRs) driven releases.

**Comment by vanniktech** [comment]
I'm already using Rx2 partially in production (RxJava 2, Retrofit, RxAndroid) and so far I didn't need to specify anything.

**Comment by artem-zinnatullin** [comment]
Yup, looks like RxJava v2 does not use `sun.misc.Unsafe` nor Java Reflection API (except in arrays creation in Subjects) -> it does not need ProGuard rules at the moment, which is great!

**Comment by artem-zinnatullin** [comment]
@akarnokd any plans to use `Unsafe` or Reflection APIs (class/field/method lookup by name) in RxJava v2?

**Comment by akarnokd** [comment]
We won't use `Unsafe` and the only reflection is to detect `setRemoveOnCancelPolicy` in scheduler setup

**Comment by artem-zinnatullin** [comment]
So, ProGuard rules for RxJava v2 are not required at the moment. I'm closing this issue and updating README.md to mention that, thanks @vanniktech and @akarnokd!
