### ISSUE TITLE
Could you explain me how to apply proguard rules of 3rd lib for main project? 

### ISSUE THREAD

**Issue by DanteAndroid** [artem-zinnatullin/RxJavaProGuardRules#54]
I have lib `c`, and I want to write a proguard rules in it, then add `c` to main project, so that main project doesn't need to add rules. Could you guide me a little bit?

**Comment by artem-zinnatullin** [comment]
>I want to write a proguard rules in it

Not sure what that means.

In simple case you just need to add rxjava proguard rules as dependency to the library `c`, so it'll be used as transit one for main project.
