### ISSUE TITLE
Can't find java.util.concurrent.ConcurrentHashMap$KeySetView keySet()

### ISSUE THREAD

**Issue by koral--** [artem-zinnatullin/RxJavaProGuardRules#62]
After upgrading `io.reactivex:rxjava:1.3.0` to `1.3.1` and  `com.artemzin.rxjava:proguard-rules:1.3.0.0` to ` 1.3.1.0` respectively, the following warning started to appear:
```Warning: rx.internal.schedulers.NewThreadWorker: can't find referenced method 'java.util.concurrent.ConcurrentHashMap$KeySetView keySet()' in library class java.util.concurrent.ConcurrentHashMap```
Compile SDK version: 26
Android Gradle plugin: `com.android.tools.build:gradle:2.4.0-alpha7`

Potential solution: add `-dontwarn rx.internal.schedulers.NewThreadWorker` rule.

**Comment by artem-zinnatullin** [comment]
@koral-- thank you for reporting, I don't see any changes related to `NewThreadWorker` in RxJava [1.3.0…1.3.1 diff](https://github.com/ReactiveX/RxJava/compare/v1.3.0...v1.3.1), but I have couple potential causes on mind:

- RxJava 1.3.1 switched to jdk8 on CI in this release
- I might had some local changes in project setup during release of proguard rules
- You're using Android Gradle Plugin `2.4.0-alpha-*` which is deprecated in favor of `3.x`

I've added this to my todo list, will check when I'll have some free time.

cc @thevery can you please check if you see this issue in your projects?

**Comment by artem-zinnatullin** [comment]
Looks like it's RxJava issue https://stackoverflow.com/questions/46174338/unable-to-create-release-build-with-rxjava-as-dependency-and-proguard-rules, author of the issue didn't use this project.

Yeah, looks like [switch to jdk8](https://github.com/ReactiveX/RxJava/commit/ed35a14b8b8c5899f292e60905e082563d516539#diff-354f30a63fb0907d4ad57269548329e3) in RxJava `.travis.yml` made [issue pointed by AnimalSniffer](https://github.com/ReactiveX/RxJava/blob/ed35a14b8b8c5899f292e60905e082563d516539/src/main/java/rx/internal/schedulers/NewThreadWorker.java#L113) real.

cc @akarnokd, @vanniktech 

Hopefully it doesn't lead to runtime crash now on Android below API 26, I'll need some time to check that.

**Comment by akarnokd** [comment]
This should not cause any runtime issues, but if you build your parent project on Java 8, you will get this warning. Unfortunately, we couldn't find any workaround because the signature of the method is different in different JDKs.

**Comment by vanniktech** [comment]
So I guess if it works on 26 just add this one to the proguard configuration file?

**Comment by artem-zinnatullin** [comment]
Well, I'm seeing that `NewThreadWorker.purgeExecutors()` fails with:

```java
java.lang.NoSuchMethodError: No virtual method 
keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView; 
in class Ljava/util/concurrent/ConcurrentHashMap; 
or its super classes (declaration of 'java.util.concurrent.ConcurrentHashMap' appears in /system/framework/core-libart.jar)
```

On Android Emulator API 21 Lollipop (Java 7 Compatible runtime).

Test scenario:

```java
System.setProperty("rx.scheduler.jdk6.purge-force", "true");

for (int i = 0; i < 10; i++) {
    Observable
            .fromCallable(new Callable<Object>() {
                @Override
                public Object call() throws Exception {
                    Log.i("~~~", System.currentTimeMillis() + "");
                    return "";
                }
            })
            .subscribeOn(Schedulers.newThread())
            .subscribe();
}
```

But app doesn't crash, exception [goes through `Exceptions.throwIfFatal(t);`](https://github.com/ReactiveX/RxJava/blob/v1.3.1/src/main/java/rx/internal/schedulers/NewThreadWorker.java#L126) and since it inherits `LinkageError`, `throwIfFatal` actually throws it and it's not getting delivered to `RxJavaHooks.onError(t);` on the next line.

---

If I switch to RxJava 1.3.0, following test scenario works fine and `purgeExecutors()` does not throw anything (I debugged it).

**Comment by akarnokd** [comment]
That's bad. I found [this](https://stackoverflow.com/questions/32954041/concurrenthashmap-crashing-application-compiled-with-jdk-8-but-targeting-jre-7) as a possible resolution, but I can't remember why we didn't use it.

**Comment by artem-zinnatullin** [comment]
Quick look at [RxJava 1.x build.gradle](https://github.com/ReactiveX/RxJava/blob/v1.3.1/build.gradle) suggests that we're not specifying Java source and target compatibility, ie:

```groovy
compileJava {
    sourceCompatibility = 1.6
    targetCompatibility = 1.6
}
```

I also think we've investigated that in past but I don't remember results, I'll look into that later today.

Another "solution" could be to call this method with reflection.

**Comment by artem-zinnatullin** [comment]
For now I'd suggest to hold upgrade to 1.3.1 until we finish investigation https://twitter.com/artem_zin/status/908416479212613633

**Comment by JakeWharton** [comment]
Specifying those two things only affects the language features you're allowed to use (source compatibility) and the version of the bytecode in the classfile (target compatibility). It doesn't not change the bootclasspath to prevent you from referencing newer APIs in the JDK. This is something fixed by JDK 9 and the `-release` flag.

You can cast `EXECUTORS` to `Map` before calling `keySet()` (downcasts are free) to get the right method signature to be emitted (at the cost of an `invokeinterface` instead of `invokevirtual`).

**Comment by JakeWharton** [comment]
Also I would recommend moving this issue to RxJava so the right people see it.

**Comment by artem-zinnatullin** [comment]
>It doesn't not change the bootclasspath to prevent you from referencing newer APIs in the JDK.

Ahh, I thought it compiles against version specific runtime lib, good to know.

>You can cast `EXECUTORS` to `Map` before calling `keySet()` (downcasts are free) to get the right method signature to be emitted (at the cost of an `invokeinterface` instead of `invokevirtual`).

Sound like a good solution!

Filed https://github.com/ReactiveX/RxJava/issues/5601, let's continue there.

**Comment by artem-zinnatullin** [comment]
Upstream RxJava issue https://github.com/ReactiveX/RxJava/issues/5601 was resolved by PR https://github.com/ReactiveX/RxJava/pull/5602.

Please skip RxJava v1.3.1 and use [v1.3.2](https://github.com/ReactiveX/RxJava/releases/tag/v1.3.2), I'm preparing release of proguard rules for 1.3.2 as well.

Thanks everyone for cooperation, that was great!
